### ISSUE TITLE
Wrong translator?

### ISSUE THREAD

**Issue by janlarres** [standardebooks/jules-verne_michael-strogoff_w-h-g-kingston#1]
The translation is attributed to W. H. G. Kingston, but according to Wikipedia the translations attributed to him were actually done by his wife, Agnes Kinloch Kingston:

https://en.wikipedia.org/w/index.php?title=William_Henry_Giles_Kingston#Financial_troubles_and_translations_of_Jules_Verne

https://en.wikipedia.org/wiki/Michael_Strogoff

It would probably be good to credit the actual translator instead.

**Comment by acabal** [comment]
We typically leave the translator as it was published. However I'll add a note to the long description.
